---
# global params
version: false
out_dir: "$PWD/ex_output"
master_fasta: "$PWD/ex_input/beta.fasta"
master_metadata: "$PWD/ex_input/beta.metadata.tsv"
n_iter: 2
seeds_file: "$PWD/ex_input/seeds.txt"
# params for sequences subsampling
subsampler:
  stop: false
  genome_matrix: "$PWD/ex_input/subsampling/matrix_genomes_unit_corrected.tsv"
  case_data: "$PWD/ex_input/subsampling/beta_scaled_global_data.tsv"
  keep_file: "$PWD/ex_input/subsampling/keep.txt"
  remove_file: "$PWD/ex_input/subsampling/remove.txt"
  filter_file: "$PWD/ex_input/subsampling/filters.tsv"
  id_column: "gisaid_epi_isl"
  geo_column: "country_exposure"
  date_column: "date"
  baseline: 0.005
  refgenome_size: 1
  max_missing: 99
  start_date: "2020-09-01"
  end_date: "2021-09-01"
  unit: "week"
# nextalign params
nextalign:
  stop: true
  in_dir: ""
  reference: "$PWD/resources/nov_sars-cov-2/reference.fasta"
  genemap: "$PWD/resources/nov_sars-cov-2/genemap.gff"
  genes: "E,M,N,ORF1a,ORF1b,ORF3a,ORF6,ORF7a,ORF7b,ORF8,ORF9b,S"
# iqtree is used in tree estimation by default
ml_tree:
  method: "iqtree"
  outgroup_fasta: ""
  stop: false
  fasttree:
    gtr: true
    boot: 0
    flags: ""
  iqtree:
    nt: "AUTO"
    m: "gtr"
    ninit: 100
    me: 0.01
    b: 0
    flags: ""
# params for initial time-calibration (should be consistent with subsequent QC steps by default)
treetime_init:
  stop: false
  clock_rate: 0.0008
  clock_std_dev: 0.00002
  reroot: "oldest"
treetime_iter:
  max_iter: 10
  max_outliers: 100